%YAML:1.0
---
#detector parameters
net_type: 5    #(0: YOLOV2, 1: YOLOV3, 2: YOLOV2_TINY, 3: YOLOV3_TINY, 4: YOLOV4, 5: YOLOV4_TINY, 6: YOLOV5)
detect_thresh: 0.25
file_model_cfg: 'yolov4-licence.cfg'
file_model_weights: 'yolov4-licence_best.weights'
inference_precison: 2   #(0: INT8, 1: FP16, 2: FP32  and 0 is deprecated)

#crnn parameters
BATCH_SIZE: 1
MAXT_BATCH_SIZE: 20    #Maximum number of vehicles supported in batch input
INPUT_H: 32
INPUT_W: 160
OUTPUT_H: 41
OUTPUT_W: 70
STD: 0.193
MEAN: 0.588
alphabet: '-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ皖沪津渝冀晋蒙辽吉黑苏浙京闽赣鲁豫鄂湘粤桂琼川贵云藏陕甘青宁新警学'   #(Dictionaries)
engine_flile: 'crnn.wts'      #(model parameter)
